Suiiii
DiscordBot-PMMP/DiscordAccount pull request #2
Opened 2024-03-20 10:33 UTC by GabBiswajit

Idk why it's need but ya it's needdddd

2024-03-21 21:43 UTC, JaxkDev commented
This needs some work at a brief overview, I apologise for the delay in responses but I am currently super busy.
I aim to review early next week.

2024-03-22 04:27 UTC, GabBiswajit commented
No problem

2024-03-30 02:01 UTC, JaxkDev requested changes

2024-03-30 02:01 UTC, JaxkDev commented on resources/config.yml
> +GUILDID: "1152905414778830848"
Few things I dont like here:
- Naming convention, all other variables are lowercase please stick to that.
- Guild-specific, the plugin itself is not tied to a single guild however this restricts it massively to a single guild.
  This may need reworking entirely to a have a dictionary of guilds -> roles
- Default values should never be personal / real data such as the ID's provided, if unsure leave blank.

2024-03-30 02:01 UTC, JaxkDev commented on src/DiscordListener.php
> +    if(!$interaction->getData() instanceof ModalSubmitData){
All of this is formatting changes which goes against the rest of the project, don't change styles in unrelated PR's it clogs it up massively and creates inconsistencies

2024-03-30 02:01 UTC, JaxkDev commented on src/DiscordListener.php
> -                $expires = $rows[0]["expiry"];
Again super hard to see what actual changes have been made when you've shuffled order of things and code style.

2024-03-30 02:01 UTC, JaxkDev commented on src/DiscordListener.php
> +  protected function updateDiscordNickname(string $userId, string $username): void {
Unrelated PR change??

Please update this PR massively, I can't review a PR whos title is 'Suiiiii' and tells me absolutely nothing about whats changed, why its changed etc.

2024-03-30 02:03 UTC, JaxkDev requested changes

2024-03-30 02:03 UTC, JaxkDev commented on resources/config.yml
>  version: 2
Changes to config require a bump, and the validation updated and a migration function added to https://github.com/DiscordBot-PMMP/DiscordAccount/blob/3e0a3c335fabffb2a9c90a7adf1ded59c50b0aa4/src/ConfigUtils.php#L26

2024-03-30 02:05 UTC, closed without merging